---
abstract: 'Template View Class'
author:
  - 'Sebastian Riedel <sri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-View-TT
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst: '5.7'
  Class::Accessor: '0'
  Data::Dump: '0'
  MRO::Compat: '0'
  Path::Class: '0'
  Template: '0'
  Template::Timer: '0'
  perl: '5.008001'
resources:
  IRC: irc://irc.perl.org/#catalyst
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/catalyst
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-View-TT
  repository: https://github.com/perl-catalyst/Catalyst-View-TT.git
version: '0.44'
x_serialization_backend: 'CPAN::Meta::YAML version 0.017'
